#ifndef __IOCTL_H__
#define __IOCTL_H__

DEFINE_GUID(DEV_GUID, 0x9477fed2, 0x86cf, 0x4d56, 0x85, 0x49, 0x62, 0x60, 0x6, 0xe3, 0x59, 0x8c);

//0 - 32767 for system, 32768 - 65536 for user
#define DEV_DRV_TYPE			80008	//设备类型

/***IO控制码(IOCTL值)-START***/
//驱动访问寄存器(BAR0)
#define IOCTL_REGISTER_READ						CTL_CODE(DEV_DRV_TYPE, 0xF00, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REGISTER_WRITE					CTL_CODE(DEV_DRV_TYPE, 0xF01, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REGISTER_READALL					CTL_CODE(DEV_DRV_TYPE, 0xF02, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REGISTER_WRITEALL					CTL_CODE(DEV_DRV_TYPE, 0xF03, METHOD_BUFFERED, FILE_ANY_ACCESS)
//用户访问寄存器(BAR1~BAR5)
#define IOCTL_USER_REGISTER_READ				CTL_CODE(DEV_DRV_TYPE, 0xF04, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_USER_REGISTER_WRITE				CTL_CODE(DEV_DRV_TYPE, 0xF05, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_USER_REGISTER_READALL				CTL_CODE(DEV_DRV_TYPE, 0xF06, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_USER_REGISTER_WRITEALL			CTL_CODE(DEV_DRV_TYPE, 0xF07, METHOD_BUFFERED, FILE_ANY_ACCESS)
//SGL(分散聚合链式)DMA
#define IOCTL_SGLDMA_CHANNEL_RESET				CTL_CODE(DEV_DRV_TYPE, 0xF0E, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SGLDMA_CHANNEL_ENABLE				CTL_CODE(DEV_DRV_TYPE, 0xF0F, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SGLDMA_CHANNEL_DISABLE			CTL_CODE(DEV_DRV_TYPE, 0xF10, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SGLDMA_CHANNEL_SETTRANSTYPE		CTL_CODE(DEV_DRV_TYPE, 0xF1F, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SGLDMA_CHANNEL_SETTRANSDIR		CTL_CODE(DEV_DRV_TYPE, 0xF20, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SGLDMA_CHANNEL_SETDMASIZE			CTL_CODE(DEV_DRV_TYPE, 0xF21, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SGLDMA_CHANNEL_SETDMACOUNT		CTL_CODE(DEV_DRV_TYPE, 0xF22, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SGLDMA_CHANNEL_SETFILEPATH		CTL_CODE(DEV_DRV_TYPE, 0xF23, METHOD_BUFFERED, FILE_ANY_ACCESS)
//获取基地址寄存器(BAR0~BAR5)信息
#define IOCTL_PCIBAR_GETRANGE					CTL_CODE(DEV_DRV_TYPE, 0xF30, METHOD_BUFFERED, FILE_ANY_ACCESS)		
#define IOCTL_PCIBAR_GETBASEADDRESS				CTL_CODE(DEV_DRV_TYPE, 0xF31, METHOD_BUFFERED, FILE_ANY_ACCESS)
//获取版本信息接口
#define IOCTL_GET_DRIVER_VERSION_INF			CTL_CODE(DEV_DRV_TYPE, 0xF40, METHOD_BUFFERED, FILE_ANY_ACCESS)
//操作配置空间的寄存器
#define IOCTL_PCI_REGISTER_WRITE				CTL_CODE(DEV_DRV_TYPE, 0xF50, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PCI_REGISTER_READ					CTL_CODE(DEV_DRV_TYPE, 0xF51, METHOD_BUFFERED, FILE_ANY_ACCESS)
//设备操作
#define IOCTL_PCI_DEVICE_INIT					CTL_CODE(DEV_DRV_TYPE, 0xF52, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PCI_DEVICE_FIND					CTL_CODE(DEV_DRV_TYPE, 0xF53, METHOD_BUFFERED, FILE_ANY_ACCESS)
//FIFO方式下进行数据传输(包括读取和写入)
#define IOCTL_PCI_FIFO_READDATA					CTL_CODE(DEV_DRV_TYPE, 0xF60, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PCI_FIFO_WRITEDATA				CTL_CODE(DEV_DRV_TYPE, 0xF61, METHOD_BUFFERED, FILE_ANY_ACCESS)
//应用程序与驱动程序之间进行事件交互
#define IOCTL_PCI_ADD_REFEVENT					CTL_CODE(DEV_DRV_TYPE, 0xF70, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PCI_DEL_REFEVENT					CTL_CODE(DEV_DRV_TYPE, 0xF71, METHOD_BUFFERED, FILE_ANY_ACCESS)
//读取状态值
#define IOCTL_PCI_GET_STAT						CTL_CODE(DEV_DRV_TYPE, 0xF80, METHOD_BUFFERED, FILE_ANY_ACCESS)	
/***IO控制码(IOCTL值)-END***/

#endif